import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Header from '../components/Header'
import Hero from '../components/Hero'
import WorkExperience from '../components/WorkExperience'

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-scroll z-0 scroll-smooth'>
      <Head>
        <title>Leo Mai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <section id='hero' className='snap-start scroll-smooth'>
      <Hero/>
      </section>
      <section id='about' className='snap-center scroll-smooth'>
      <About/>
      </section>
      <section id='experience' className='snap-center scroll-smooth'>
      <WorkExperience/>
      </section>
      {/* about */}
      {/* experience */}
      {/* skills */}
      {/* Projects */}
      {/* contact me */}
    </div>
  )
}

export default Home
