import type { NextPage } from 'next'
import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Header from '../components/Header'
import Hero from '../components/Hero'
import Projects from '../components/Projects'
import Skills from '../components/Skills'
import WorkExperience from '../components/WorkExperience'

const Home: NextPage = () => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory z-0 scroll-smooth overflow-y-scroll overflow-x-hidden scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#009DCF]/80'>
      <Head>
        <title>Leo Mai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <section id='hero' className='snap-start scroll-smooth'>
      <Hero/>
      </section>
      <section id='about' className='snap-center scroll-smooth'>
      <About/>
      </section>
      <section id='experience' className='snap-center scroll-smooth'>
      <WorkExperience/>
      </section>
      <section id='skills' className='snap-start scroll-smooth'>
      <Skills/>
      </section>
      <section id='projects' className='snap-start scroll-smooth'>
      <Projects/>
      </section>
      <section id='contact' className='snap-start scroll-smooth'>
      <Contact/>
      </section>


      
      {/* contact me */}
    </div>
  )
}

export default Home
